experiment:
  experiment_name: "acoustic_emission_classification"
  num_runs: 5
  seed: 42
  results_dir: "./results"
  checkpoint_dir: "./ckpt"

data:
  root_dir: "./data/resized/measurementSeries_B"
  imbalance_factors:
    "05cNm": 0.005
    "10cNm": 0.005
    "20cNm": 0.005
    "30cNm": 1.0
    "40cNm": 1.0
    "50cNm": 1.0
    "60cNm": 1.0
  test_samples_per_class: 100
  train_val_split: 0.8
  batch_size: 32
  num_workers: 4

model:
  model_name: "googlenet"
  num_classes: 7
  pretrained: true

training:
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adamw"
  checkpoint_path: "./ckpt/best_model.pth"
  # Removed duplicate model settings (they're already in model section)

# Optional GAN augmentation settings (used only when --gan-checkpoint is provided)
gan:
  latent_dim: 200
  num_classes: 7
  d_model_dim: 128
  augmentation_strategy: "balance"  # "balance" or "oversample"
  
# Optional checkpoint evaluation settings
checkpoint_evaluation:
  checkpoint_interval: 30
  evaluation_results_dir: "./results/gan_evaluation"