gan:
  # Model parameters
  latent_dim: 200
  num_classes: 7
  d_model_dim: 128
  
  # Training parameters
  batch_size: 64
  num_epochs: 2000
  d_updates: 1
  
  # Optimizer parameters
  g_lr: 1e-5      # Generator learning rate
  d_lr: 1e-6      # Discriminator learning rate
  beta1: 0.5      # Adam beta1
  beta2: 0.9      # Adam beta2
  
  # Loss parameters
  lambda_gp: 15.0  # Gradient penalty coefficient
  
  # Class imbalance ratios
  imbalance_ratios:
    "05": 0.005
    "10": 0.005
    "20": 0.005
    "30": 1.0
    "40": 1.0
    "50": 1.0
    "60": 1.0
  
  # Checkpoint and visualization settings
  checkpoint_interval: 30    # Save checkpoint every N epochs
  visualization_interval: 100 # Generate samples every N epochs
  
  # Data generation settings
  samples_per_class: 1000   # Number of samples to generate per class

paths:
  # Input data directory
  data_root: "/root/test/output_dir_single_ver6_0221_sensorB_224size/measurementSeries_D"
  
  # Output directories
  checkpoint_dir: "./checkpoints/gan"
  results_dir: "./results/gan"
  generated_data_dir: "./data/generated"

experiment:
  # Experiment settings
  seed: 42
  resume_training: true
  
  # Device settings
  device: "auto"  # "auto", "cuda", or "cpu"